server:
  port: 8083
  servlet:
    context-path: /${spring.application.name}
spring:
  datasource:
    url: jdbc:mysql://42.194.203.220:3306/hospital?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: "@liuJ0523"
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  cloud:
    nacos:
      discovery:
        server-addr: 42.194.203.220:8848
  application:
    name: service-product
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto